USE [NOME_BANCO_DE_DADOS]
GO

DROP TABLE [dbo].[CAMPO]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAMPO](
	[Code] [nvarchar](50) NOT NULL,
	[NOME] [nvarchar](200) NULL,
	[DESCR] [nvarchar](200) NULL,
	[CODE_TBL] [nvarchar](200) NULL,
 CONSTRAINT [KCAMPO_PR] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



DROP TABLE [dbo].[TABELA]
GO

/****** Object:  Table [dbo].[@JBC_B1TBL]    Script Date: 02/09/2020 02:58:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TABELA](
	[Code] [nvarchar](50) NOT NULL,
	[NOME] [nvarchar](200) NULL,
	[DESCR] [nvarchar](200) NULL,
 CONSTRAINT [KTABELA_PR] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

